[package]
name = "bq41z50"
version = "0.1.0"
description = "Platform-agnostic async Rust driver for the Texas Instruments BQ41Z50 battery fuel gauge."
edition = "2024"
license = "MIT"
repository = "https://github.com/OpenDevicePartnership/bq41z50"
documentation = "https://docs.rs/bq41z50"
readme = "README.md"
keywords = ["battery", "fuel-gauge", "i2c", "embedded-hal", "driver"]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
rust-version = "1.94"

[dependencies]
device-driver = "2.1.0"
embedded-batteries-async = "0.3.4"
embedded-hal-async = "1.0.0"

[lints.clippy]
suspicious = "deny"
correctness = "deny"
perf = "deny"
style = "deny"

[features]
defmt-03 = []

[dev-dependencies]
tokio = { version = "1.50.0", features = ["full"] }
embedded-hal-mock = { version = "0.11.1", features = ["embedded-hal-async"] }
pico-de-gallo-hal = "0.7.0"
